// Generated from the registered Nest OpenAPI. JSON dates are strings.
export interface ApiSuccess<T>{success:true;message:string;data:T}
export interface ApiError{success:false;message:string|string[];error:string}
export type HealthDatabaseDto = {"status": "CONNECTED" | "DISCONNECTED";
"latencyMs": number;};
export type HealthMemoryDto = {"rssMb": number;
"heapUsedMb": number;};
export type HealthDto = {"status": "UP" | "DEGRADED";
"apiVersion": "v1";
"commit": string;
"timestamp": string;
"uptimeSeconds": number;
"database": HealthDatabaseDto;
"memory": HealthMemoryDto;
"environment": string;};
export type DashboardUserDto = {"id": number;
"name": string;
"role": string;};
export type DashboardStatsDto = {"projects": number;
"openTasks": number;
"pendingDeliverables": number;
"overdueTasks": number;
"meetings": number;
"quotes": number;
"prospects": number;};
export type DashboardProjectDto = {"id": number;
"name": string;
"status": string;
"totalDeliverables": number;
"approvedDeliverables": number;
"progress": number;};
export type DashboardDeliverableDto = {"id": number;
"projectId": number;
"title": string;
"status": string;
"dueDate": string;};
export type DashboardRevenueDto = {"currency": string;
"confirmedAmountMinor": string;};
export type DashboardTaskDto = {"id": number;
"projectId": number;
"title": string;
"status": string;
"assigneeId": (number) | null;
"dueDate": (string) | null;};
export type DashboardMeetingDto = {"id": number;
"status": string;
"scheduledAt": (string) | null;
"timezone": string;};
export type DashboardWorkloadDto = {"userId": number;
"openTasks": number;};
export type DashboardDistributionDto = {"label": string;
"count": number;};
export type DashboardIntegrationDto = {"name": string;
"status": "CONFIGURED" | "NOT_CONFIGURED";
"connectivity": string;};
export type ClientDashboardDto = {"generatedAt": string;
"user": DashboardUserDto;
"stats": DashboardStatsDto;
"projects": Array<DashboardProjectDto>;
"deliverables": Array<DashboardDeliverableDto>;
"revenue": Array<DashboardRevenueDto>;
"tasks": Array<DashboardTaskDto>;
"meetings": Array<DashboardMeetingDto>;
"workload": Array<DashboardWorkloadDto>;
"usersByRole": Array<DashboardDistributionDto>;
"projectsByStatus": Array<DashboardDistributionDto>;
"integrations": Array<DashboardIntegrationDto>;
"database": string;
"previewLimit": number;};
export type DeveloperDashboardDto = {"generatedAt": string;
"user": DashboardUserDto;
"stats": DashboardStatsDto;
"projects": Array<DashboardProjectDto>;
"deliverables": Array<DashboardDeliverableDto>;
"revenue": Array<DashboardRevenueDto>;
"tasks": Array<DashboardTaskDto>;
"meetings": Array<DashboardMeetingDto>;
"workload": Array<DashboardWorkloadDto>;
"usersByRole": Array<DashboardDistributionDto>;
"projectsByStatus": Array<DashboardDistributionDto>;
"integrations": Array<DashboardIntegrationDto>;
"database": string;
"previewLimit": number;};
export type ProductOwnerDashboardDto = {"generatedAt": string;
"user": DashboardUserDto;
"stats": DashboardStatsDto;
"projects": Array<DashboardProjectDto>;
"deliverables": Array<DashboardDeliverableDto>;
"revenue": Array<DashboardRevenueDto>;
"tasks": Array<DashboardTaskDto>;
"meetings": Array<DashboardMeetingDto>;
"workload": Array<DashboardWorkloadDto>;
"usersByRole": Array<DashboardDistributionDto>;
"projectsByStatus": Array<DashboardDistributionDto>;
"integrations": Array<DashboardIntegrationDto>;
"database": string;
"previewLimit": number;};
export type AdminDashboardDto = {"generatedAt": string;
"user": DashboardUserDto;
"stats": DashboardStatsDto;
"projects": Array<DashboardProjectDto>;
"deliverables": Array<DashboardDeliverableDto>;
"revenue": Array<DashboardRevenueDto>;
"tasks": Array<DashboardTaskDto>;
"meetings": Array<DashboardMeetingDto>;
"workload": Array<DashboardWorkloadDto>;
"usersByRole": Array<DashboardDistributionDto>;
"projectsByStatus": Array<DashboardDistributionDto>;
"integrations": Array<DashboardIntegrationDto>;
"database": string;
"previewLimit": number;};
export type SuperAdminDashboardDto = {"generatedAt": string;
"user": DashboardUserDto;
"stats": DashboardStatsDto;
"projects": Array<DashboardProjectDto>;
"deliverables": Array<DashboardDeliverableDto>;
"revenue": Array<DashboardRevenueDto>;
"tasks": Array<DashboardTaskDto>;
"meetings": Array<DashboardMeetingDto>;
"workload": Array<DashboardWorkloadDto>;
"usersByRole": Array<DashboardDistributionDto>;
"projectsByStatus": Array<DashboardDistributionDto>;
"integrations": Array<DashboardIntegrationDto>;
"database": string;
"previewLimit": number;};
export type MeetingsPageDto = {"page": number;
"limit": number;
"totalItems": number;
"totalPages": number;
"items": Array<DashboardMeetingDto>;};
export type Object = {};
export type TaskDto = {"id": number;
"projectId": number;
"title": string;
"description": string;
"status": "TODO" | "IN_PROGRESS" | "DONE";
"assigneeId": (number) | null;
"createdById": number;
"dueDate": (string) | null;
"createdAt": string;
"updatedAt": string;};
export type TaskPageDto = {"page": number;
"limit": number;
"totalItems": number;
"totalPages": number;
"items": Array<TaskDto>;};
export type CreateTaskDto = {"title": string;
"description"?: string;
"assigneeId"?: (unknown) | null;
"dueDate"?: (unknown) | null;};
export type UpdateTaskDto = {"title"?: string;
"description"?: string;
"assigneeId"?: (unknown) | null;
"dueDate"?: (unknown) | null;
"status"?: "TODO" | "IN_PROGRESS" | "DONE";};
export type ResourceDto = {"id": number;
"projectId": number;
"createdById": number;
"name": string;
"url": string;
"createdAt": string;
"updatedAt": string;};
export type ResourcePageDto = {"page": number;
"limit": number;
"totalItems": number;
"totalPages": number;
"items": Array<ResourceDto>;};
export type CreateResourceDto = {"name": string;
"url": string;};
export type UpdateResourceDto = {"name"?: string;
"url"?: string;};
export type WorkLogDto = {"id": number;
"projectId": number;
"userId": number;
"taskId": (number) | null;
"date": string;
"minutes": number;
"summary": string;
"createdAt": string;};
export type WorkLogPageDto = {"page": number;
"limit": number;
"totalItems": number;
"totalPages": number;
"items": Array<WorkLogDto>;};
export type CreateWorkLogDto = {"taskId"?: number;
"date": string;
"minutes": number;
"summary": string;};
export type CvFileDto = {"id": string;
"url": string;
"filename": string;
"mimeType": string;
"sizeBytes": number;
"cvUrl": string;};
export type PrivateFileDto = {"id": string;
"url": string;
"filename": string;
"mimeType": string;
"sizeBytes": number;};
export type PublicTeamDto = {"displayName": string;
"biography": string;
"specialty": string;
"photoUrl"?: string;
"approved": boolean;
"consentRecorded": boolean;};
export type EditQuoteDto = {"expectedUpdatedAt": string;
"fullName"?: string;
"phone"?: string;
"company"?: string;
"notes"?: string;};
export type ObservationDto = {"versionId": number;
"text": string;};
export type ContactDto = {"name": string;
"email": string;
"phone"?: string;
"subject": string;
"message": string;};
export type ActivationDto = {"token": string;
"password": string;
"acceptedTerms": true;
"termsVersion": string;
"privacyVersion": string;};
export type RequestActivationDto = {"email": string;};
export type InviteClientDto = {"name": string;
"email": string;};
export type UpdateOwnUserDto = {"name"?: string;
"acceptedTerms"?: true;
"termsVersion"?: string;
"privacyVersion"?: string;};
export type UpdateClientProfileDto = {"dni"?: string;
"age"?: number;
"phone"?: string;
"ruc"?: string;};
export type UpdateDeveloperProfileDto = {"technologyIds"?: Array<number>;};
export type UpdateProductOwnerProfileDto = {};
export type UpdateAdminProfileDto = {};
export type UpdateUserDto = {};
export type CreateUserDto = {"name": string;
"email": string;
"password": string;
"role": "CLIENT" | "DEVELOPER" | "PRODUCT_OWNER" | "ADMIN";
"acceptedTerms": boolean;
"termsVersion": string;
"privacyVersion": string;};
export type LoginDto = {"email": string;
"password": string;};
export type RegisterDto = {"name": string;
"email": string;
"password": string;
"acceptedTerms": boolean;
"termsVersion": string;
"privacyVersion": string;};
export type RefreshDto = {"refreshToken": string;};
export type ForgotPasswordDto = {"email": string;};
export type ResetPasswordDto = {"token": string;
"newPassword"?: string;
"password"?: string;};
export type CreateCategoryDto = {};
export type UpdateCategoryDto = {};
export type CreateTechnologyDto = {};
export type UpdateTechnologyDto = {};
export type CreateProjectDto = {"name": string;
"slug": string;
"shortDescription": string;
"description": string;
"problem"?: (unknown) | null;
"solution"?: (unknown) | null;
"objective"?: (unknown) | null;
"features"?: Array<string>;
"categoryId": number;
"technologyIds"?: Array<number>;
"status"?: "DRAFT" | "IN_DEVELOPMENT" | "IN_REVIEW" | "COMPLETED" | "ARCHIVED";
"developmentDate"?: (unknown) | null;
"clientName"?: (unknown) | null;
"demoUrl"?: (unknown) | null;
"externalUrl"?: (unknown) | null;
"coverImageUrl"?: (unknown) | null;
"isFeatured"?: boolean;
"displayOrder"?: number;};
export type UpdateProjectDto = {"name"?: string;
"slug"?: string;
"shortDescription"?: string;
"description"?: string;
"problem"?: (unknown) | null;
"solution"?: (unknown) | null;
"objective"?: (unknown) | null;
"features"?: Array<string>;
"categoryId"?: number;
"technologyIds"?: Array<number>;
"status"?: "DRAFT" | "IN_DEVELOPMENT" | "IN_REVIEW" | "COMPLETED" | "ARCHIVED";
"developmentDate"?: (unknown) | null;
"clientName"?: (unknown) | null;
"demoUrl"?: (unknown) | null;
"externalUrl"?: (unknown) | null;
"coverImageUrl"?: (unknown) | null;
"isFeatured"?: boolean;
"displayOrder"?: number;};
export type InstallmentDto = {"percentageBasisPoints": number;
"dueDate": string;
"milestone": string;};
export type OfficialQuoteDto = {"clientUserId": number;
"amountMinor": number;
"currency": string;
"scope": string;
"observations"?: string;
"installments": Array<InstallmentDto>;};
export type PaymentEventDto = {"amountMinor": number;
"currency": string;};
export type CreateServiceDto = {"name": string;
"slug": string;
"shortDescription": string;
"description": string;
"icon"?: (unknown) | null;
"imageUrl"?: (unknown) | null;
"displayOrder"?: number;
"isFeatured"?: boolean;
"isActive"?: boolean;};
export type UpdateServiceDto = {"name"?: string;
"slug"?: string;
"shortDescription"?: string;
"description"?: string;
"icon"?: (unknown) | null;
"imageUrl"?: (unknown) | null;
"displayOrder"?: number;
"isFeatured"?: boolean;
"isActive"?: boolean;};
export type CreateQuoteDto = {};
export type TeamApplicationDto = {};
export type QuoteOptionDto = {"code": string;};
export type QuoteContactDto = {"fullName": string;
"email": string;
"phone": string;
"company"?: string;};
export type CreatePublicQuoteDto = {"solutionType": string;
"options": Array<QuoteOptionDto>;
"deliveryMode"?: "NORMAL" | "URGENT" | "FLEXIBLE";
"contact": QuoteContactDto;
"notes"?: string;};
export type PublicQuoteResponseDto = {"code": string;
"status": "RECEIVED";
"pricingStatus": "PENDING_RULES" | "CALCULATED";
"amountMinor": (number) | null;
"currency": (string) | null;
"pricingVersion": (string) | null;
"createdAt": string;};
export type CreatePublicQuoteResponseDto = {"success": boolean;
"message": string;
"data": PublicQuoteResponseDto;};
export type LinkQuoteDto = {"publicCode": string;};
export type UpdateProspectStatusDto = {"status": "NEW" | "CONTACTED" | "QUALIFIED" | "CONVERTED" | "LOST";};
export type AssignProspectAdvisorDto = {"advisorProfileId": (number) | null;};
export type UpdateMeetingStatusDto = {};
export type RescheduleMeetingDto = {};
export type BookMeetingDto = {};
export type SetAdvisorVisibilityDto = {"isPublicAdvisor": boolean;};
export type KickoffDto = {};
export type ScheduleKickoffDto = {};
export type AddMemberDto = {};
export type ProjectTeamDto = {};
export type AssignProductOwnerDto = {};
export type CreateDeliverableDto = {"title": string;
"description": string;
"milestoneOrder": number;
"dueDate": string;};
export type SubmitDeliverableDto = {"fileUrl"?: string;
"externalLink"?: string;};
export type ReviewDeliverableDto = {"decision": "APPROVE" | "OBSERVE";
"feedbackNotes"?: string;
"comments"?: string;};
export type SubmitEvidenceDto = {"pdfUrl"?: string;
"fileUrl"?: string;
"videoUrl": string;
"notes"?: string;};
export type RequestClientMeetingDto = {};
export type AcceptQuoteDto = {"versionId": number;
"accepted": true;};
export type CreateCardChargeDto = {};
export type InterviewDecisionDto = {"decision": "ACCEPTED" | "REJECTED";
"reason"?: string;};
export type AssignInterviewDto = {"adminProfileId": number;};
export type RejectTeamApplicationDto = {"reason": string;};
export type MemberContributionItemDto = {"userId": number;
"percentage": number;
"description": string;};
export type SaveContributionsDto = {"contributions": Array<MemberContributionItemDto>;};